OP-AL/opal

- src/Pages/Home/Home.tsx
> home branch 수정테스트

- src/Pages/Home/Home.tsx
- src/Pages/MyPage/MyAccount.tsx
- src/Pages/MyPage/MyInfo.tsx
- src/Pages/MyPage/MyPage.tsx
- src/Pages/MyPage/MyPurchase.tsx
- src/Pages/Routes.tsx
- src/index.tsx
- src/redux/reducer/reducer.tsx
- src/redux/store.tsx
230614_Harim_feat: MyPage 탭 추가, Redux설명주석 및 tab 추가
> 230614_Harim_feat: MyPage 탭 추가, Redux설명주석 및 tab 추가

- src/App.tsx
- src/Components/Footer/Footer.tsx
- src/Pages/Home/Home.tsx
- src/Pages/SignIn/SignIn.tsx
- src/Pages/SignUp/SignUp.tsx
**[파일 수정]**
src/App.tsx
src/Pages/Home/Home.tsx
src/Pages/SignIn/SignIn.tsx
src/Pages/SignUp/SignUp.tsx
**[파일 추가]**
src/Components/Footer/Footer.tsx
header, footer 컴포넌트가 어떤 페이지에서든 공통으로 적용되게 수정함
> 230614_Eunji_feat: header, footer 공통영역으로 고정

- src/Components/Header/Header.tsx
- src/Pages/SignIn/SignIn.tsx
- src/Pages/SignUp/SignUp.tsx
- src/Styles/Sign.scss
- src/api.ts
> 230621_Eunji_feat: api분리, scss 추가 2

- src/Pages/MyPage/MyInfo.tsx
230622_Harim_feat:MyInfo.tsx 레이아웃 생성
> 230622_Harim_feat:MyInfo.tsx 레이아웃 생성

- src/Components/Header/Header.tsx
- src/Pages/Home/Home.tsx
- src/Pages/SignIn/SignIn.tsx
- src/Pages/SignUp/SignUp.tsx
- src/api.ts
- src/redux/reducer/reducer.tsx
230622_Eunji_feat: 로그아웃 추가, 회원정보 reducer추가
> 230622_Eunji_feat: 로그아웃 추가, 회원정보 reducer추가

- package-lock.json
- package.json
- src/Pages/MyPage/MyAccount.tsx
- src/Pages/SignIn/SignIn.tsx
230623_Harim_feat: accessToken cookie저장코드추가
> 230623_Harim_feat: accessToken cookie저장코드추가

- src/Components/Header/Header.tsx
- src/Pages/Home/Home.tsx
- src/Pages/MyPage/MyAccount.tsx
- src/Pages/MyPage/MyInfo.tsx
- src/Pages/SignIn/SignIn.tsx
- src/api.ts
- src/redux/reducer/reducer.tsx
230625_Eunji_feat: 마이페이지 -내정보수정 완료
> 230625_Eunji_feat: 마이페이지 -내정보수정 완료

- src/Pages/MyPage/MyAccount.tsx
- src/Pages/MyPage/MyPage.tsx
- src/Pages/MyPage/MyPurchase.tsx
- src/api.ts
230625_harim_feat: 내계좌 추가 Modal 기능 업그레이드, 마이페이지 Tab버튼 antd로 변경
> 230625_harim_feat: 내계좌 추가 Modal 기능 업그레이드, 마이페이지 Tab버튼 antd로 변경

- package-lock.json
- src/Pages/MyPage/MyAccount.tsx
- src/Pages/ProductDetail/ProductDetail.tsx
- src/Pages/Routes.tsx
- src/Styles/ProductDetail.module.scss
- src/api.ts
- src/redux/reducer/reducer.tsx
230626_Geumyeop_Feat: Productdetail 컴포넌트 레이아웃, 단일 제품 상세 조회 기능 추가
> 230626_Geumyeop_Feat: Productdetail 컴포넌트 레이아웃, 단일 제품 상세 조회 기능 추가

- src/Pages/ProductDetail/ProductDetail.tsx
- src/redux/reducer/reducer.tsx
230628_Geumyeop_Feat. 예약 관련 옵션 reducer 추가
> 230628_Geumyeop_Feat. 예약 관련 옵션 reducer 추가

- src/Pages/MyPage/MyAccount.tsx
- src/Pages/MyPage/MyPurchase.tsx
- src/api.ts
230628_harim_feat: 마이페이지 구매내역 기능완성
> 230628_harim_feat: 마이페이지 구매내역 기능완성

- src/Components/Contents/QuickMenu.tsx
- src/Components/Header/Header.tsx
- src/Pages/Home/Home.tsx
- src/Pages/MyPage/MyPage.tsx
- src/Pages/PaymentCheck/PaymentCheck.tsx
- src/Pages/SignIn/SignIn.tsx
- src/Pages/SignUp/SignUp.tsx
- src/Styles/QuickMenu.scss
- src/Styles/Sign.scss
- src/redux/reducer/reducer.tsx
230628_Eunji_feat: 퀵메뉴, 예약확인증 추가
> 230628_Eunji_feat: 퀵메뉴, 예약확인증 추가

- src/Components/Common/NotFound.tsx
- src/Components/Contents/QuickMenu.tsx
- src/Components/Contents/SearchBar.tsx
- src/Components/Contents/VoucherModal.tsx
- src/Pages/MyPage/MyAccount.tsx
- src/Pages/MyPage/MyPage.tsx
- src/Pages/MyPage/MyPurchase.tsx
- src/Pages/Routes.tsx
- src/Pages/SignUp/SignUp.tsx
- src/api.ts
- src/redux/reducer/reducer.tsx
230629_Eunji_fix: 회원가입 로직 수정, NotFound 페이지 추가
> 230629_Eunji_fix: 회원가입 로직 수정, NotFound 페이지 추가

- src/Components/Contents/Category.tsx
- src/Components/Contents/Counter.tsx
- src/Components/Contents/SearchBar.tsx
- src/Components/Header/Header.tsx
- src/Pages/Home/Home.tsx
- src/Pages/MyPage/MyPage.tsx
- src/Pages/MyPage/MyPurchase.tsx
- src/Pages/ProductDetail/ProductDetail.tsx
- src/Pages/ProductList/ProductItem.tsx
- src/Pages/ProductList/ProductList.tsx
- src/api.ts
- src/redux/reducer/reducer.tsx
> 230629_harim_fix: 검색기능수정

- src/Pages/MyPage/MyAccount.tsx
230629_Eunji_fix: MyAccount 문구 수정
> 230629_Eunji_fix: MyAccount 문구 수정

- src/Pages/ProductDetail/ProductDetail.tsx
- src/Pages/ProductPayment/ProductPayment.tsx
230630_harim_fix: 결제페이지 새로고침 변수 초기화문제 수정
> 230630_harim_fix: 결제페이지 새로고침 변수 초기화문제 수정

- src/Components/Contents/QuickMenu.tsx
- src/Components/Contents/VoucherModal.tsx
- src/Pages/MyPage/MyAccount.tsx
- src/Pages/ProductPayment/ProductPayment.tsx
> 230630_Eunji_feat: 결제완료 모달추가

- src/Pages/ProductPayment/ProductPayment.tsx
230630_harim_fix: 결제api body 데이터 오류 수정
> 230630_harim_fix: 결제api body 데이터 오류 수정

- src/Components/Contents/QuickMenu.tsx
- src/Components/Contents/VoucherModal.tsx
- src/Pages/ProductPayment/ProductPayment.tsx
- src/Styles/Modal.scss
- src/api.ts
230630_Eunji_feat: modal 디자인 추가, 코드정리
> 230630_Eunji_feat: modal 디자인 추가, 코드정리

- src/Components/Contents/Category.tsx
- src/Components/Contents/SearchBar.tsx
- src/Components/Header/Header.tsx
- src/Pages/MyPage/MyPurchase.tsx
- src/Pages/ProductDetail/ProductDetail.tsx
- src/Pages/ProductPayment/ProductPayment.tsx
- src/Styles/Category.scss
- src/redux/reducer/reducer.tsx
230630_Geumyeop_Fix: 상세페이지 DatePicker 초기화 오류 수정
- Assets > Fonts 폴더 삭제
- error 확인용을 제외한 console.log 삭제
- import 했으나 사용하지 않는 내용들 삭제
> 230630_Geumyeop_Fix: 상세페이지 DatePicker 초기화 오류 수정

- src/Pages/MyPage/MyInfo.tsx
- src/Pages/ProductDetail/ProductDetail.tsx
- src/Pages/ProductPayment/ProductPayment.tsx
230630_harim_fix: 닉네임수정오류, 결제페이지 새로고침 productId값 가져오기 수정
> 230630_harim_fix: 닉네임수정오류, 결제페이지 새로고침 productId값 가져오기 수정

- src/Components/Contents/QuickMenu.tsx
230630_Eunji_fix: 퀵메뉴 현재 예약만 나오게 수정
> 230630_Eunji_fix: 퀵메뉴 현재 예약만 나오게 수정

- src/Pages/ProductList/ProductItem.tsx
230630_harim_fix: 검색목록 로딩중일때 spinner추가
> 230630_harim_fix: 검색목록 로딩중일때 spinner추가

- package.json
230630_harim_fix: package.json build script 수정1
> 230630_harim_fix: package.json build script 수정1

- README.md
230630_Geumyeop_Docs: README.md 1차 수정
> 230630_Geumyeop_Docs: README.md 1차 수정

- src/Components/Common/NotFound.tsx
- src/Components/Contents/SearchBar.tsx
- src/Components/Contents/VoucherModal.tsx
- src/Components/Header/Header.tsx
- src/Styles/Category.scss
- src/Styles/Header.scss
- src/Styles/Modal.scss
- src/Styles/NotFound.scss
- src/Styles/common.scss
> 230630_Eunji_fix: scss수정

- src/Components/Footer/Footer.tsx
- src/Styles/Event.scss
- src/Styles/Footer.scss
- src/Styles/common.scss
230630_Geumyeop_Fix: 메인페이지 지금 뜨는 장소 이미지 수정, footer 프로필 사진 변경
> 230630_Geumyeop_Fix: 메인페이지 지금 뜨는 장소 이미지 수정, footer 프로필 사진 변경

- src/Components/Footer/Footer.tsx
- src/Styles/Footer.scss
- src/Styles/NotFound.scss
230630_Geumyeop_Fix: Not Found 페이지 레이아웃 변경, footer scss 변경
> 230630_Geumyeop_Fix: Not Found 페이지 레이아웃 변경, footer scss 변경

- src/Components/Footer/Footer.tsx
- src/Styles/Footer.scss
- src/Styles/NotFound.scss
230630_Geumyeop_Fix: Footer, Not Found 변경
> 230630_Geumyeop_Fix: Footer, Not Found 변경

- src/Pages/ProductDetail/ProductDetail.tsx
- src/Styles/ProductDetail.module.scss
230630_Geumyeop_Fix: 상세페이지 card width값 변경
> 230630_Geumyeop_Fix: 상세페이지 card width값 변경

- src/Styles/ProductItem.scss
230703_Geumyeop_Fix: 제품 검색 페이지 가격 정렬 수정
> 230703_Geumyeop_Fix: 제품 검색 페이지 가격 정렬 수정

- README.md
230703_Eunji_docs: Update Readme
> 230703_Eunji_docs: Update Readme

- src/Pages/MyPage/MyInfo.tsx
- src/Styles/MyInfo.scss
- src/Styles/MyPage.scss
> 230703_siwoo_fix:scss 수정 배포

- 404.html
> 230703_harim_404.html파일 추가

- src/Pages/MyPage/MyInfo.tsx
230703_Eunji_fix: 배포 후 새로고침 오류
> 230703_Eunji_fix: 배포 후 새로고침 오류

- src/Pages/Routes.tsx
230703_Eunji_fix: 배포 후 새로고침 오류3
NotFound 라우터 임시 삭제
> 230703_Eunji_fix: 배포 후 새로고침 오류3

- src/Pages/MyPage/MyInfo.tsx
- src/Styles/SelectionAccount.scss
- src/Styles/common.scss
230704_siwoo_fix:btn,datepicker수정
> 230704_siwoo_fix:btn,datepicker수정

- README.md
230729 README Update
금엽님 작성해주신 부분 업데이트 해써요!!
> 230729 README Update
